services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file: ./.env
    environment:
      - DB_URI=${MONGODB_ATLAS_URI}  # Use the full MongoDB Atlas URI from .env
    depends_on:
      - frontend

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
